package com.a9ae0b01f0ffc.tpn.conf

import com.a9ae0b01f0ffc.commons.implementation.config.T_common_conf

class T_tpn_conf extends T_common_conf{

    String GC_TPN_CLASSES_CONF
    String GC_BLACK_BOX_CONFIG
    String GC_THREAD_CONFIG_FILE_NAME
    String GC_REQUEST_METHOD
    String GC_USER_AGENT
    String GC_ACCEPT_LANGUAGE
    String GC_CONTENT_TYPE
    String GC_CYCLE_INTERVAL_MILLISECONDS
    String GC_RESEND_INTERVAL_SECONDS
    String GC_MYSQL_CONNECTION_STRING
    String GC_MYSQL_USERNAME
    String GC_MYSQL_PASSWORD
    String GC_MYSQL_DRIVER
    String GC_MODE
    String GC_MAX_RETRY_COUNT
    String GC_POLL_LIMIT
    String GC_PAYLOAD_TYPE
    String GC_CHECK_DUPLICATES
    String GC_USE_CONVERSION_TEMPLATES
    String GC_SQL_SESSION_REFRESH_INTERVAL_MILLISECONDS
    String GC_TEMPLATE_NAME_SCHEME
    String GC_TEMPLATE_NAME_BANK
    String GC_TPN_EXTERNAL_USERNAME
    String GC_TPN_EXTERNAL_PASSWORD

    T_tpn_conf(String i_conf_file_name) {
        super(i_conf_file_name)
        GC_TPN_CLASSES_CONF = GC_CONST_CONF.GC_TPN_CLASSES_CONF(GC_TPN_CLASSES_CONF)
        GC_BLACK_BOX_CONFIG = GC_CONST_CONF.GC_BLACK_BOX_CONFIG(GC_BLACK_BOX_CONFIG)
        GC_THREAD_CONFIG_FILE_NAME = GC_CONST_CONF.GC_THREAD_CONFIG_FILE_NAME(GC_THREAD_CONFIG_FILE_NAME)
        GC_REQUEST_METHOD = GC_CONST_CONF.GC_REQUEST_METHOD(GC_REQUEST_METHOD)
        GC_USER_AGENT = GC_CONST_CONF.GC_USER_AGENT(GC_USER_AGENT)
        GC_ACCEPT_LANGUAGE = GC_CONST_CONF.GC_ACCEPT_LANGUAGE(GC_ACCEPT_LANGUAGE)
        GC_CONTENT_TYPE = GC_CONST_CONF.GC_CONTENT_TYPE(GC_CONTENT_TYPE)
        GC_CYCLE_INTERVAL_MILLISECONDS = GC_CONST_CONF.GC_CYCLE_INTERVAL_MILLISECONDS(GC_CYCLE_INTERVAL_MILLISECONDS)
        GC_RESEND_INTERVAL_SECONDS = GC_CONST_CONF.GC_RESEND_INTERVAL_SECONDS(GC_RESEND_INTERVAL_SECONDS)
        GC_MYSQL_CONNECTION_STRING = GC_CONST_CONF.GC_MYSQL_CONNECTION_STRING(GC_MYSQL_CONNECTION_STRING)
        GC_MYSQL_USERNAME = GC_CONST_CONF.GC_MYSQL_USERNAME(GC_MYSQL_USERNAME)
        GC_MYSQL_PASSWORD = GC_CONST_CONF.GC_MYSQL_PASSWORD(GC_MYSQL_PASSWORD)
        GC_MYSQL_DRIVER = GC_CONST_CONF.GC_MYSQL_DRIVER(GC_MYSQL_DRIVER)
        GC_MODE = GC_CONST_CONF.GC_MODE(GC_MODE)
        GC_POLL_LIMIT = GC_CONST_CONF.GC_POLL_LIMIT(GC_POLL_LIMIT)
        GC_PAYLOAD_TYPE = GC_CONST_CONF.GC_PAYLOAD_TYPE(GC_PAYLOAD_TYPE)
        GC_CHECK_DUPLICATES = GC_CONST_CONF.GC_CHECK_DUPLICATES(GC_CHECK_DUPLICATES)
        GC_MAX_RETRY_COUNT = GC_CONST_CONF.GC_MAX_RETRY_COUNT(GC_MAX_RETRY_COUNT)
        GC_USE_CONVERSION_TEMPLATES = GC_CONST_CONF.GC_CONVERT_TO_GFS_FORMAT(GC_USE_CONVERSION_TEMPLATES)
        GC_SQL_SESSION_REFRESH_INTERVAL_MILLISECONDS = GC_CONST_CONF.GC_SQL_SESSION_REFRESH_INTERVAL_MILLISECONDS(GC_SQL_SESSION_REFRESH_INTERVAL_MILLISECONDS)
        GC_TEMPLATE_NAME_SCHEME = GC_CONST_CONF.GC_TEMPLATE_NAME_SCHEME(GC_TEMPLATE_NAME_SCHEME)
        GC_TEMPLATE_NAME_BANK = GC_CONST_CONF.GC_TEMPLATE_NAME_BANK(GC_TEMPLATE_NAME_BANK)
        GC_TPN_EXTERNAL_USERNAME = GC_CONST_CONF.GC_TPN_EXTERNAL_USERNAME(GC_TPN_EXTERNAL_USERNAME)
        GC_TPN_EXTERNAL_PASSWORD = GC_CONST_CONF.GC_TPN_EXTERNAL_PASSWORD(GC_TPN_EXTERNAL_PASSWORD)
    }

}
